app/controllers/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, Response
from flask_login import login_required, logout_user, login_user, current_user
from app.services.user_mgmt import validate_credentials, get_user_by_email, is_advisor, is_student
from app.services.login_mgmt import User

from colorama import Fore

auth_bp = Blueprint("auth", __name__, url_prefix="/auth")

"""
This file is for routes that are related to authentication, like LOGIN and LOUGOUT.

Generally, we don't want to put anything in here besides LOGIN and LOGOUT.
"""

@auth_bp.route("/login_dashboard")
def login_dashboard():
    """
    This is for the Student Login button in the header.\n
    if user is currently logged in, then it redirects to dashboard, if not logs in and redirects to homepage
    """
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.dashboard_redirect", email=current_user.id))
    
    return redirect(url_for('auth.student_login'))
        

# LOGIN ROUTE > 127.0.0.1:8888/auth/login
@auth_bp.route("/login", methods=["GET", "POST"])
def student_login():
    # If the user is sending data to the /login page via the forms
    if request.method == "POST":
        email = request.form["email_address_data"]
        password = request.form["password_data"]

        # Get 'next' from the form data (for POST requests)
        next_page = request.form.get("next")
        # print(Fore.BLUE, "GRAB ME:", next_page, Fore.RESET)

        if validate_credentials(email, password) == True:
            
            if not is_student(email):
                return render_template("auth/student_login.html", error_code=403, error_msg="You are not authorized to use student login portal!")
            
            user_data = get_user_by_email(email)

            # Create a new user object
            user = User(email, user_data)

            # Send user object into login_user
            login_user(user)

            if next_page and next_page != "/auth/logout":
                print(Fore.GREEN, "auth_routes.py: Login successful! Redirecting...", Fore.RESET)
                return redirect(next_page)

            print(Fore.GREEN, "auth_routes.py: Login successful! Redirecting...", Fore.RESET)
            return redirect(url_for("main.homepage"))
        
        else:
            return render_template("auth/student_login.html", error_code=404, error_msg="Invalid credentials! Please check email or password again!")

    # Return statement IF user sends a GET request
    return render_template("auth/student_login.html")

@auth_bp.route("/advisor_login", methods=["GET", "POST"])
def advisor_login():
    # If the user is sending data to the /login page via the forms
    if request.method == "POST":
        email = request.form["email_address_data"]
        password = request.form["password_data"]

        # Get 'next' from the form data (for POST requests)
        next_page = request.form.get("next")
        # print(Fore.BLUE, "GRAB ME:", next_page, Fore.RESET)

        if validate_credentials(email, password) == True:
            
            if not is_advisor(email):
                return render_template("auth/advisor_login.html", error_code=403, error_msg="You are not authorized to use advisor login portal!")
            
            user_data = get_user_by_email(email)

            # Create a new user object
            user = User(email, user_data)

            # Send user object into login_user
            login_user(user)

            if next_page and next_page != "/auth/logout":
                print(Fore.GREEN, "auth_routes.py: Login successful! Redirecting...", Fore.RESET)
                return redirect(next_page)

            print(Fore.GREEN, "auth_routes.py: Login successful! Redirecting...", Fore.RESET)
            return redirect(url_for("main.homepage"))
        
        else:
            return render_template("auth/advisor_login.html", error_code=404, error_msg="Invalid credentials! Please check email or password again!")

    # Return statement IF user sends a GET request
    return render_template("auth/advisor_login.html")

# LOGOUT ROUTE > 127.0.0.1:8888/auth/logout
@auth_bp.route("/logout")
@login_required # just for integrity reasons, it feels weird to logout_user a user that isnt logged in
def logout():
    logout_user()
    return redirect(url_for("main.homepage"))

#  FORGOT PASSWORD ROUTE > 127.0.0.1:8888/auth/forgot
@auth_bp.route('/forgot')
def forgot_pass():
    """
    IM GOING TO BE REFACTORING THE ENTIRE FILE HIERARCHY, IT IS JUST A MESS TO LOOK AT
    A COMPLETE EYE SORE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    """
    
    return render_template("auth/forgot_password.html")

templates/testing/basedashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='/css/basedashboard.css') }}">
        {% block links %}
        <!-- Links -->
        {% endblock %}
        <title>
            {% block title %}
            <!-- Page Title -->
            {% endblock %}
        </title>
        
</head>
<body>
    <!-- Header -->
    <header class="prof-field">
        <nav class="prof-cont">
            <ul>
                <li id="profile">👤</li>
                <li id="logout" style="display: none;">
                    <a href="{{ url_for('auth.logout') }}">
                    <button>Logout</button>
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    {% block content %} 
    <!-- Child Content -->
    {% endblock %}
</body>
</html>

templates/testing/confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Services</title>
    <link rel="stylesheet" href="../static/css/confirmation.css">
    <link rel="stylesheet" href="../static/confirmation.css">
</head>
<body>
    <header class="default">
        <nav class="portalnav">
            <ul>
                <li><a href="http://learn.bcit.ca/">Learning Hub</a></li>
                <li><a href="https://my.bcit.ca/">myBCIT</a></li>
                <li><a href="https://www.bcit.ca/current-students/">Students</a></li>
                <li><a href="https://www.bcit.ca/faculty-staff/">Staff</a></li>
                <li><a href="https://www.bcit.ca/events/">Events</a></li>
            </ul>
        </nav>
        <div class="sitenav">
        <div class="logo">
            <a class="home" href="https://www.bcit.ca/" aria-label="bcit logo" role="navigation">
                <svg class="logo" viewBox="0 0 95 85" xmlns="https://www.w3.org/2000/svg"><path fill="#003c71" d="M0 0h84.8v84.8H0z"/><path fill="#fff" d="M8.6 56.4V27.2h7.2c6.7 0 9.7 2.2 9.7 7.6 0 3-1.3 5.1-3.8 6.2v.1c3.3 1.2 4.5 3.7 4.5 7 0 6.7-4.3 8.4-10 8.4H8.6v-.1zm7.4-17c2.5 0 4.7-.9 4.7-4.1 0-3.1-2.3-3.7-4.7-3.7h-2.7v7.8H16zm.5 12.7c3.4 0 4.8-1.2 4.8-4.3 0-3.2-1.6-4.5-4.8-4.5h-3.2v8.8h3.2zm30.9-5.2c-.9 6.5-3.6 9.9-8.9 9.9-7 0-9.3-5.7-9.3-15.1 0-8.4 2.4-14.8 9.3-14.8 5.6 0 7.8 3.5 8.6 9.4l-4.5.4c-.6-3.7-1.9-5.5-4-5.5-3 0-4.5 3.1-4.5 10.5 0 8.1 1.3 10.8 4.5 10.8 2.3 0 3.7-2.1 4.3-6.1l4.5.5zm4.1 9.5V27.2h4.8v29.2h-4.8zm14.8 0V31.6h-6v-4.4h16.8v4.4h-6v24.8h-4.8z"/><path fill="#003c71" d="M89.426 3.253c.462 0 .84-.13.84-.625 0-.478-.408-.566-.826-.566h-.64v1.19h.626zm.885 2.15l-.77-1.554H88.8v1.554h-.71V1.454h1.304c.973 0 1.572.333 1.572 1.16 0 .48-.248.858-.742 1.046l.899 1.743h-.812zM92.126 3.5c0-1.584-.99-2.86-2.716-2.86-1.743 0-2.744 1.276-2.744 2.86 0 1.627 1 2.862 2.744 2.862 1.727 0 2.716-1.235 2.716-2.862zM86 3.5C86 1.54 87.288 0 89.41 0c2.12 0 3.398 1.54 3.398 3.5 0 1.916-1.278 3.5-3.398 3.5C87.288 7 86 5.416 86 3.5z"/></svg>
            </a>
        </div>
        <ul>
            <li><a href="https://www.bcit.ca/study/">Programs & Courses</a></li>
            <li><a href="https://www.bcit.ca/admission/">Admission</a></li>
            <li><a href="https://www.bcit.ca/student-services/">Student Services</a></li>
            <li><a href="https://www.bcit.ca/applied-research/">Research</a></li>
            <li><a href="https://www.bcit.ca/about/">About BCIT</a></li>
        </ul>
    </header>
    <main>
        <div class="conf">
            <h1>Confirmation</h1>
                <form class="receipt">
                    <label for="bcit-id">BCIT ID:</label><br>
                    <input type="text" id="bcit-id" name="bcit-id"><br><br>
                    <label for="first-name">First Name:</label><br>
                    <input type="text" id="first-name" name="first-name"><br><br>
                    <label for="last-name">Last Name:</label><br>
                    <input type="text" id="last-name" name="last-name"><br><br>
                    <label for="email">Email:</label><br>
                    <input type="text" id="email" name="email"><br><br>
                </form>
        </div>
        <button>Submit</button>
    </main>
</body>
</html>

templates/testing/student_dashboard.html
{% extends "base_dashboard.html" %}

{% block links %}
<link rel="stylesheet" href="../static/css/testdashboard.css">
{% endblock %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<main> 
    {% if not appts %}
    <h2>No Appointments</h2>
    {% else %}
    <h1>Welcome, {{ user.name }} {{ user.surname }}</h1>
    <div class="upcoming">
        <h2>Upcoming Appointments</h2>
    </div>
    {% for appt in appts %}
    <div class="info">
        <div class="user-info">
            <p><strong>Date:{{ appt.date }}</strong></p>
            <p><strong>Time: {{ appt.start_time }} - {{ appt.end_time }}</strong></p>
            <p><strong>Advisor Name: {{ advisor.name }}</strong></p>
            <p><strong>Details:</strong></p>
            <div class="button-group">
                <button>Cancel</button>
                <a href="comment.html"><button>Continue</button></a> 
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</main>
{% endblock %}

templates/testing/student_login_test.html
{% extends "base.html" %}

{% block links %}
<link rel="stylesheet" href="../static/css/testadvisor_login.css">
{% endblock %}

{% block title %}
Student Login Portal — BCIT
{% endblock %}

{% block content %}
<!-- please make ur indentations and tag closing consistent, i beg you -->
<main>
    <div class="login-container">
        <h2>Welcome to BCIT Advisor Booking</h2>
        <p>Student Login Portal</p>
        <form method="post" action="{{ url_for('auth.student_login') }}">

            <!-- THIS IS TO CATCH THE NEXT PARAM IN POST REQUEST. READ DOC.md FOR MORE INFORMATION -->
            {% if request.args.get('next') %}
                <input type="hidden" name="next" value="{{ request.args.get('next') }}">
            {% endif %}
            
            <label>Email:</label>
            <input type="email" placeholder="name@my.bcit.ca" name="email_address_data" required>

            <label>Password:</label>
            <input type="password" placeholder="••••••••" name="password_data" required>
            
            <button type="submit">Login</button>
            <br>
            <p class="forgotPassword"><a href="{{ url_for('auth.forgot_pass') }}">Forgot Password?</a></p>
        </form>
        <p class="advisorlogin-text">
        <b> For Advisors:</b> <a href="{{ url_for('auth.advisor_login', next=request.args.get('next')) }}"">Advisor Login Portal</a>
        </p>
        <h2>{{ err_code }}</h2>
        <p>{{ err_msg }}</p>
    </div>
</main>     
{% endblock %}

templates/testing/testcomment.html
{% extends "basedashboard.html" %}
<!-- is this a seperate page for any particular reason? -->

{% block links %}
<link rel="stylesheet" href="../static/css/testcomment.css">
{% endblock %}

{% block title %}
Comments
{% endblock %}

{% block content %}
<main> 
    <div class="comment">
        <h2>Comment</h2>
    </div>
    <div class="info">
        <div class="user-info">
            <p><strong>Name:</strong></p>
            <p><strong>Email:</strong></p>
            <textarea id="comment-field" name="comment" cols="25" rows="20" placeholder="State your comment here..."></textarea>
            <div class="button-group">
                <button>Send</button>
            </div>
        </div>
    </div> 
</main>
{% endblock %}

templates/testing/testforgot.html
{% extends "base.html" %}

{% block links %}
<link rel="stylesheet" href="../static/css/testforgot.css">
{% endblock %}

{% block title %}
Forgot Password — BCIT
{% endblock %}

{% block content %}
<main>
    <div class="input-container">
        <h2>Forgot your Password?</h2>
        <p>Please enter your recovery email address below. An email will be sent to you with instructions to reset your password.</p>
        <form>
            <label>Recovery Email:</label>
            <input type="email" placeholder="name@address.com" required>
            <button type="submit">Submit</button>
        </form>
        <p class="advisorlogin-text">
        <p class="contact-service-link"><a href="https://www.bcit.ca/it-services/">Contact IT Services</a></p>
        </p>
    </div>
</main>
{% endblock %}