app/controllers/dash_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from db import db
from app.models import Appointments, Users, Services
from app.services.login_mgmt import User
from app.services.user_mgmt import is_student, is_advisor
from datetime import datetime, timedelta
from colorama import Fore 

dash_bp = Blueprint("dashboard", __name__, url_prefix="/dashboard")
# DASHBOARD ROUTE

@dash_bp.route("/")
@login_required
def dashboard_redirect():
    user_email = current_user.id
        
    if not user_email:
        return redirect(url_for('main.error'))

    if is_student(user_email):
        return redirect(url_for('dashboard.student_dashboard', email=user_email))

    if is_advisor(user_email):
        advisor = db.session.execute(db.select(Users).where(Users.email == current_user.id))
        return redirect(url_for('dashboard.advisor_dashboard', advisor_id=advisor.id))        


@dash_bp.route("/student/<string:email>")
@login_required
def student_dashboard(email):
    """
    Student dashboard route
    Displays the student's information and their appointments.
    """
    user = db.session.execute(db.select(Users).where(Users.email == email)).scalar()
    
    # Searches for appointments with same user email
    user_appointments = db.session.execute(db.select(Appointments).where(Appointments.user_email == email)).scalars()
    len_appts = list(db.session.execute(db.select(Appointments).where(Appointments.user_email == email)).scalars())
    return render_template("dash/student_dashboard.html", user=user, appts=user_appointments, appt_length=len_appts)

@dash_bp.route("/advisor/<string:email>")
@login_required
def advisor_dashboard(email):
    """
    Advisor dashboard route
    Displays the advisor's information and their appointments.
    """
    user = db.session.execute(db.select(Users).where(Users.email == email)).scalar()
    user_appts = db.session.execute(db.select(Appointments).where(Appointments.advisor_id == user.id)).scalars()
    len_appts = list(db.session.execute(db.select(Appointments).where(Appointments.advisor_id == user.id)).scalars())
    return render_template("dash/advisor_dashboard.html", user=user, appts=user_appts, appt_length=len_appts)


# cancel booking route
@dash_bp.route("/cancel/<int:appt_id>")
@login_required
def cancel_appt(appt_id):
    appt = db.session.execute(db.select(Appointments).where(Appointments.id == appt_id)).scalar()

    db.session.delete(appt)
    db.session.commit()

    flash(f"Appointment has been canceled")
    return redirect(url_for('dashboard.dashboard_redirect'))

@dash_bp.route("/edit/<int:appt_id>", methods=["GET", "POST"])
@login_required
def edit_comment(appt_id):
    user = db.session.execute(db.select(Users).where(Users.email == current_user.id))
    appt = db.session.execute(db.select(Appointments).where(Appointments.id == appt_id)).scalar()

    if request.method == "POST":
        new_comment = request.form.get("comment")
        appt.comment = new_comment
        db.session.commit()
        flash("Appointment details updated.")
        return redirect(url_for("dashboard.dashboard_redirect"))

    return render_template("dash/student_edit.html", appt=appt, user=user)

app/controllers/main_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from db import db
from app.models import Users, Services

main_bp = Blueprint("main", __name__)

"""
These routes are for pages that don't technically fall under any category of page. 

For example, /login page fall under auth_routes, however, /homepage page wouldn't fall under any category, so we place /homepage here.
"""

# INDEX/HOME ROUTE > http://127.0.0.1:8888/
@main_bp.route("/")
def homepage():
    return render_template("index.html")


# SERVICES ROUTE > http://127.0.0.1:8888/services
@main_bp.route("/services")
# make a route have the requirement of a user being auth'ed !!!TEMP BECAUSE GUEST USER SHOULD BE ABLE TO ACCESS SERVICES, PROMPT THEM TO LOGIN TO BOOK SERVICE
def services():
    """
    flask route to access services page
    it will query all services and will be able to access each service name and each advisor in every service
    """
    services = db.session.execute(db.select(Services)).scalars()
    navs = db.session.execute(db.select(Services)).scalars()
    # used 2 differnet variables since we needed 2 different for loops

    return render_template("main/services.html", services=services, navs=navs)

templates/dash/advisor_dashboard.html
{% extends "base_dashboard.html" %}

{% block links %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block title %}
Dashboard
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/student.js')}}"></script>
{% endblock %}

{% block content %}
    <main> 
        <h1>Welcome, {{ user.name }} {{ user.surname }}</h1>
        <div class="upcoming">
            {% if appt_length|length > 0 %}
        <h2>Upcoming Appointments</h2>
        {% else %}
        <h2>No Appointments</h2>
        {% endif %}
        
        {% with messages = get_flashed_messages()%}
            {% if messages%}
                {% for message in messages%}
                    <p style="background-color: lightgreen; padding: 20px; font-size: 25px; margin-bottom: 20px; border-radius: 5px;">{{message}}</p>
                {%endfor%}
            {%endif%}
        {%endwith%}
        </div>
        <div class="main-display">
        {% for appt in appts %}
        <div class="info">
            <div class="user-info">
                <h2>Appointment Details:</h2>
                <p><strong>Date:</strong>
                    <br>{{ appt.date }}</p>
                <p><strong>Time:</strong>
                    <br>{{ appt.start_time }} - {{ appt.end_time }}</p>
                <p><strong>Advisor:</strong>
                    <br>{{ appt.advisor.name }} {{ appt.advisor.surname }} </p>
                <p><strong>Meeting Type:</strong>
                    <br>{{ appt.meeting_type}}</p>
                <p><strong>Details:</strong>
                    <br>{{ appt.comment }}</p>
                <div class="button-group">
                    <button class="button-choices" onclick="cancelAppointment()">Cancel Appointment</button>
                </div>
            </div> 
                <div id="cancelModal" class="modal">
                    <div class="modal-content">
                        <span class="close" onclick="closeModal()">&times;</span>
                        <h3>Are you sure you want to cancel the appointment?</h3>
                        <a href="{{ url_for('dashboard.cancel_appt', appt_id=appt.id)}}">
                        <button class="topButton" onclick="confirmCancel()">Yes</button>
                        </a>
                        <button class="topButton" onclick="closeModal()">No</button>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </main>
{% endblock %}

templates/dash/student_dashboard.html
{% extends "base_dashboard.html" %}

{% block links %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block title %}
Dashboard
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/student.js')}}"></script>
{% endblock %}

{% block content %}
    <main> 
        <h1>Welcome, {{ user.name }} {{ user.surname }}</h1>
        <div class="upcoming">
            {% if appt_length|length > 0 %}
        <h2>Upcoming Appointments</h2>
        
        <a href="{{ url_for('main.services') }}"><button class="bookAppt" style="margin-bottom: 30px;">Book an Appointment</button></a>
        {% else %}
        <h2>No Appointments</h2>
        
        <a href="{{ url_for('main.services') }}"><button class="bookAppt" style="margin-bottom: 30px;">Book an Appointment</button></a>
        {% endif %}
        
        {% with messages = get_flashed_messages()%}
            {% if messages%}
                {% for message in messages%}
                    <p style="background-color: lightgreen; padding: 20px; font-size: 25px; margin-bottom: 20px; border-radius: 5px; width: fit-content;">{{message}}</p>
                {%endfor%}
            {%endif%}
        {%endwith%}
        </div>
        <div class="main-display">
        {% for appt in appts %}
        <div class="info">
            <div class="user-info">
                <h2>Appointment Details:</h2>
                <p><strong>Date:</strong>
                    <br>{{ appt.date }}</p>
                <p><strong>Time:</strong>
                    <br>{{ appt.start_time }} - {{ appt.end_time }}</p>
                <p><strong>Advisor:</strong>
                    <br>{{ appt.advisor.name }} {{ appt.advisor.surname }} </p>
                <p><strong>Meeting Type:</strong>
                    <br>{{ appt.meeting_type}}</p>
                <p><strong>Details:</strong>
                    <br>{{ appt.comment }}</p>
                <div class="button-group">
                    <button class="button-choices" onclick="cancelAppointment()">Cancel Appointment</button>
                    <a href="{{ url_for('dashboard.edit_comment', appt_id=appt.id) }}"><button class="button-choices">Edit Details</button></a>
                </div>
            </div> 
                <div id="cancelModal" class="modal">
                    <div class="modal-content">
                        <span class="close" onclick="closeModal()">&times;</span>
                        <h3>Are you sure you want to cancel the appointment?</h3>
                        <a href="{{ url_for('dashboard.cancel_appt', appt_id=appt.id)}}">
                        <button class="topButton" onclick="confirmCancel()">Yes</button>
                        </a>
                        <button class="topButton" onclick="closeModal()">No</button>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </main>
{% endblock %}

templates/dash/student_edit.html
{% extends "base_dashboard.html" %}

{% block links %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<main>
    <div class="info">
        <div class="user-info">
            <h2>Edit Appointment Details:</h2>
            <p><strong>Date:</strong>
                <br>{{ appt.date }}</p>
                <p><strong>Time:</strong>
                    <br>{{ appt.start_time }} - {{ appt.end_time }}</p>
                    <p><strong>Advisor:</strong>
                        <br>{{ appt.advisor.name }} {{ appt.advisor.surname }} </p>
                        <p><strong>Meeting Type:</strong>
                            <br>{{ appt.meeting_type}}</p>
                            <p><strong>Details:</strong>
                                <br>
                                <form method="post">
                                <textarea name="comment" id="details">{{ appt.comment }}</textarea>
                                <button>Save Changes</button>
                            </form>
                        </p>
                        <a href="{{ url_for('dashboard.student_dashboard', email=current_user.id) }}"><button>Go Back</button></a>
                    </main>
{% endblock %}